const swaggerAutogen = require('swagger-autogen')()
const dotenv = require('dotenv')
dotenv.config();
const outputFile = './swagger_output.json'
const endpointsFiles = [
    './routes/AutorizacionRoutes.js',
    './routes/CiudadRoutes.js',
    './routes/ConsentimientoRoutes.js',
    './routes/ConvenioRoutes.js',
    './routes/DepartamentoRoutes.js',
    './routes/DoctorRoutes.js',
    './routes/EmpleadoRoutes.js',
    './routes/EntidadRoutes.js',
    './routes/EntidadDoctorRoutes.js',
    './routes/FormaDePagoEntidadRoutes.js',
    './routes/InformacionRXRoutes.js',
    './routes/PaqueteRoutes.js',
    './routes/PaqueteServicioRoutes.js',
    './routes/ProcesoRoutes.js',
    './routes/ServicioRoutes.js',
    './routes/SexoRoutes.js',
    './routes/TipoConsentimientoRoutes.js',
    './routes/TipoDocumentoRoutes.js',
    './routes/TipoEmpleadoRoutes.js',
    './routes/TipoFacturacionRoutes.js',
    './routes/TipoNotaCreditoRoutes.js',
    './routes/TipoPagoRoutes.js',
    './routes/TipoPrefEntregaRoutes.js',
    './routes/TransaccionRoutes.js',
    './routes/TransaccionServicioRoutes.js',
    './routes/UsuarioRoutes.js',
]

const port = process.env.HOST_FOR_SWAGGER || 'localhost:4000'

const doc = {
    info: {
        version: "1.0.0",
        title: "API para radioxenter",
        description: "Documentation automatically generated by the <b>swagger.autogen</b> module."
    },
    host: port,
    basePath: "/api",
    schemes: ['http','https'],
    consumes: ['application/json','multipart/form-data'],
    produces: ['application/json'],
    definitions: {
        CreateEmpleado:{
            "nombres_empleado": "",
            "apellidos_empleado": "",
            "documento_empleado": 0,
            "direccion_empleado": "",
            "fnacimiento_empleado": "dd/MM/YYYYY",
            "telefono_empleado": "",
            "correo_empleado": "email@email.com",
            "contrasenia_empleado": "",
            "usuario_empleado": "",
            "cod_tipo_empleado": 0,
            "cod_tipo_documento": 0
        },
        Login:{
            "usuario_empleado": "",
            "contrasenia_empleado": ""
        },
        Ciudad:{
            "cod_ciudad": 0,
            "nom_ciudad": "string",
            "cod_departamento": 0
        },
        Departamento:{
            "cod_departamento": 0,
            "nom_departamento": "",
        },
        Doctor:{
            "cod_doctor": 0,
            "nombres_doctor": "",
            "apellidos_doctor": "",
            "direccion_doctor": "",
            "telefono_doctor": "",
            "documento_doctor": 0,
            "correo_doctor": "email@email.com",
            "cod_tipo_documento": 0,
            "cod_tipo_pref_entrega": 0
        },
        Empleado:{
            "cod_empleado": 0,
            "nombres_empleado": "",
            "apellidos_empleado": "",
            "documento_empleado": 0,
            "direccion_empleado": "",
            "fnacimiento_empleado": "dd/MM/YYYYY",
            "telefono_empleado": "",
            "correo_empleado": "email@email.com",
            "contrasenia_empleado": "",
            "usuario_empleado": "",
            "cod_tipo_empleado": 0,
            "cod_tipo_documento": 0
        },
        Entidad:{
            "cod_entidad": 0,
            "razon_social_entidad": "",
            "nombre_comercial_entidad": "",
            "nit_entidad": "",
            "direccion_entidad": "",
            "telefono_entidad": "",
            "nombre_representante": "",
            "cedula_representante": 0,
            "telefono_representante": "",
            "correo_representante": "email@email.com",
            "nombre_contacto": "",
            "cedula_contacto": "",
            "telefono_contacto": "",
            "correo_contacto": "",
            "cod_forma_de_pago_entidad": 0,
            "cod_tipo_facturacion": 0
        },
        EditarConvenioEntidad:{
            "servicios_convenio":[1,2,3],
            "valores_servicios":[1000,2000,3000],
            "fecha_inicial_convenio":"dd/MM/YYYYY",
            "fecha_final_convenio":"dd/MM/YYYYY"
        },
        FormaDePagoEntidad:{
            "cod_forma_de_pago_entidad": 0,
            "nombre_forma_de_pago_entidad": ""
        },
        InformacionRX: {
            "cod_informacion_rx":0,
            "nit_rx":"",
            "razon_social_rx":"",
            "nombre_comercial":""
        },
        Paquete:{
            "cod_paquete":0,
            "nombre_paquete": "",
            "precio_paquete": 0
        },
        EditarPaqueteServicio:{
            "servicios_paquete": [0],
        },
        Servicio: {
            "cod_servicio": 0,
            "nombre_servicio": "",
            "descripcion_servicio": "",
            "precio_servicio": 0,
            "iva_servicio": 0
        },
        Sexo:{
            "cod_sexo": 0,
            "nombre_sexo": ""
        },
        TipoConsentimiento:{
            "cod_tipo_consentimiento":0,
            "nombre_tipo_consentimiento":""
        },
        TipoDocumento:{
            "cod_tipo_documento": 0,
            "nombre_tipo_documento": "",
        },
        TipoEmpleado:{
            "cod_tipo_empleado": 0,
            "nombre_tipo_empleado": "",
        },
        TipoFacturacion:{
            "cod_tipo_facturacion": 0,
            "nombre_tipo_facturacion": "",
        },
        TipoNotaCredito:{
            "cod_tipo_nota_credito":0,
            "nombre_tipo_nota_credito":""
        },
        Convenio: {
            "valor_servicio": 0,
            "fecha_inicial_convenio": "yyyy-MM-dd",
            "fecha_final_convenio":"yyyy-MM-dd",
            "cod_entidad": 0,
            "cod_servicio": 0
        },
        ConvenioUpdate:{
            "valor_servicio": 0,
            "fecha_inicial_convenio": "yyyy-MM-dd",
            "fecha_final_convenio": "yyyy-MM-dd",
        },
        EntidadDoctor:{
            "cod_entidad": 0,
            "cod_doctor": 0
        },
        PaqueteServicio:{
            "cod_paquete":0,
            "cod_servicio":0
        },
        Proceso:{
            "estado_proceso": "",
            "cod_usuario": 0
        },
        TipoPago:{
            "nombre_tipo_pago": ""
        },
        TipoPreferenciaEntrega: {
            "nombre_tipo_pref_entrega":""
        },
        Transaccion: {
            "documento_usuario": 0,
            "valor_transaccion": 0,
            "fecha_transaccion": "yyyy-MM-dd",
            "nombres_acudiente": "",
            "apellidos_acudiente": "",
            "documento_acudiente": 0,
            "parentesco_acudiente": "",
            "cod_entidad_doctor": 0
        },
        TransaccionServicio: {
            "cod_transaccion": 0,
            "cod_servicio": 0
        },
        Usuario: {
            "nombres_usuario": "",
            "apellidos_usuario": "",
            "telefono_usuario": "",
            "direccion_usuario": "",
            "documento_usuario": 0,
            "ocupacion_usuario": "",
            "fecha_nacimiento_usuario": "yyyy-MM-dd",
            "correo_usuario": "",
            "genero_usuario": "",
            "celular_usuario": "",
            "cod_sexo": 0,
            "cod_tipo_documento": 0,
            "cod_ciudad": 0,
            "cod_tipo_pref_entrega": 0
        },
        Consentimiento: {
            "cod_transaccion": 0,
            "ubicacion_consentimiento": "",
            "cod_tipo_consentimiento": 0
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles,doc).then(() => {
    require('./index.js')
})

//   https://medium.com/swlh/automatic-api-documentation-in-node-js-using-swagger-dd1ab3c78284